### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by crawfordsm** [jason-neal/eniric#114]
Wiki installation and configuration:  There is slightly different information between the two.   Suggest keeping one set of docs rather than two or making sure they are both updated simultaneously. 

The data download for example is only in the READMe and not the wiki though that is very useful information

Link: https://github.com/openjournals/joss-reviews/issues/1053

**Comment by jason-neal** [comment]
Have move documentation all to read the docs.
Updated the installation and configuration documentation.
