### ISSUE TITLE
Bug when running download_eniric_data.sh

### ISSUE THREAD

**Issue by crawfordsm** [jason-neal/eniric#115]
Error when connecting to dropbox:
Connecting to www.dropbox.com|162.125.6.1|:443... connected.
ERROR: cannot verify www.dropbox.com's certificate, issued by ‘CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to www.dropbox.com insecurely, use `--no-check-certificate'.

**Comment by crawfordsm** [comment]
Link: https://github.com/openjournals/joss-reviews/issues/1053

**Comment by jason-neal** [comment]
Added option to pass `--no-check-certificate` to the download_eniric_data.sh script incase this is encountered.

In commit d594c415667adf1aeb9

```
$ scripts/download/download_eniric_data.sh -h

   Usage:
       scripts/download/download_eniric_data.sh [--no-check-certificates]

   Downloads data for eniric from dropbox and the phoenix aces library.


```
