### ISSUE TITLE
Documentation link to example directory? 

### ISSUE THREAD

**Issue by crawfordsm** [jason-neal/eniric#120]
The examples directory was very useful to take a look at things.  It would be useful to have a high level description and page linking to each of the notebooks and explaining what they do.   More consistent description of each of the notebooks would also make the notebooks more useful. 

Link: https://github.com/openjournals/joss-reviews/issues/1053

**Comment by jason-neal** [comment]
https://eniric.readthedocs.io/en/latest/examples.html
